# Embeds compiled shader bytecode (fxc .cso files) into a C++ header, so the
# plugin never needs a shader compiler at runtime.
#
# Invoked as a script:
#   cmake -DOUTPUT=<header> -DBYTECODE_DIR=<dir> -DSHADERS="Cull.hlsl:CSCompact;..." -P EmbedShaderBytecode.cmake
#
# Each "file:entry" item reads <BYTECODE_DIR>/<C identifier of file_entry>.cso
# and becomes an entry in GWP::PrecompiledShaders::kAll.

if (NOT DEFINED OUTPUT OR NOT DEFINED BYTECODE_DIR OR NOT DEFINED SHADERS)
	message(FATAL_ERROR "EmbedShaderBytecode.cmake requires OUTPUT, BYTECODE_DIR and SHADERS")
endif ()

set(_body "")
set(_table "")

foreach (_shader IN LISTS SHADERS)
	string(REPLACE ":" ";" _parts "${_shader}")
	list(GET _parts 0 _file)
	list(GET _parts 1 _entry)
	string(MAKE_C_IDENTIFIER "${_file}_${_entry}" _ident)

	file(READ "${BYTECODE_DIR}/${_ident}.cso" _hex HEX)
	if ("${_hex}" STREQUAL "")
		message(FATAL_ERROR "${BYTECODE_DIR}/${_ident}.cso is empty")
	endif ()
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")

	string(APPEND _body "\tinline constexpr std::uint8_t k_${_ident}[] = { ${_bytes} };\n")
	string(APPEND _table "\t\t{ \"${_file}\"sv, \"${_entry}\"sv, k_${_ident} },\n")
endforeach ()

set(_content "// Generated by cmake/EmbedShaderBytecode.cmake - do not edit.\n#pragma once\n\nnamespace GWP::PrecompiledShaders\n{\n\tstruct Entry\n\t{\n\t\tstd::string_view file;\n\t\tstd::string_view entryPoint;\n\t\tstd::span<const std::uint8_t> bytecode;\n\t};\n\n${_body}\n\tinline constexpr Entry kAll[] = {\n${_table}\t};\n}\n")

# Only touch the file when the content changes to avoid needless rebuilds.
if (EXISTS "${OUTPUT}")
	file(READ "${OUTPUT}" _old)
	if ("${_old}" STREQUAL "${_content}")
		return()
	endif ()
endif ()

file(WRITE "${OUTPUT}" "${_content}")
