# Embeds HLSL sources into a C++ header so the plugin ships as a single DLL.
#
# Invoked as a script:
#   cmake -DOUTPUT=<header> -DSHADER_DIR=<dir> -DSHADERS="a.hlsl;b.hlsli" -P GenerateShaderHeader.cmake
#
# Each file becomes a null-terminated byte array (byte arrays avoid MSVC's
# string-literal length limit) plus an entry in GWP::EmbeddedShaders::kAll.

if (NOT DEFINED OUTPUT OR NOT DEFINED SHADER_DIR OR NOT DEFINED SHADERS)
	message(FATAL_ERROR "GenerateShaderHeader.cmake requires OUTPUT, SHADER_DIR and SHADERS")
endif ()

set(_body "")
set(_table "")

foreach (_file IN LISTS SHADERS)
	get_filename_component(_name "${_file}" NAME)
	string(MAKE_C_IDENTIFIER "${_name}" _ident)

	file(READ "${SHADER_DIR}/${_file}" _hex HEX)
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")

	string(APPEND _body "\tinline constexpr char k_${_ident}[] = { ${_bytes}0x00 };\n")
	string(APPEND _table "\t\t{ \"${_name}\"sv, std::string_view{ k_${_ident}, sizeof(k_${_ident}) - 1 } },\n")
endforeach ()

set(_content "// Generated by cmake/GenerateShaderHeader.cmake - do not edit.\n#pragma once\n\nnamespace GWP::EmbeddedShaders\n{\n\tstruct Entry\n\t{\n\t\tstd::string_view name;\n\t\tstd::string_view source;\n\t};\n\n${_body}\n\tinline constexpr Entry kAll[] = {\n${_table}\t};\n}\n")

# Only touch the file when the content changes to avoid needless rebuilds.
if (EXISTS "${OUTPUT}")
	file(READ "${OUTPUT}" _old)
	if ("${_old}" STREQUAL "${_content}")
		return()
	endif ()
endif ()

file(WRITE "${OUTPUT}" "${_content}")
